"""
OpenAPI-driven contract tests for the DCC API (discover → generate → run → reports).

Pytest suites under projects/dcc/tests remain separate; this package runs the
autogenerated GET suite and optional performance runs.

**Entry points:** ``python -m framework.contract_runner`` (``main_dcc``), or ``main_dcc_perf`` in ``dcc_perf_cli``.
"""
