"""
OpenAPI-driven contract tests for the DCC API (discover → generate → run → reports).

Pytest suites under projects/dcc/tests remain separate; this package runs the
autogenerated GET suite and optional performance runs.
"""
