"""
OpenAPI-driven contract tests for the DCC API (discover → generate → run → reports).

Pytest suites under projects/dcc/tests remain separate; this package runs the
autogenerated GET suite and optional performance runs.

**Entry points:** ``python -m framework.contract_runner`` (DCC contract), ``python -m framework.contract_runner.dcc.perf_cli``,
``python -m framework.contract_runner.federation.cli`` (Federation contract); implementations live under
``framework.contract_runner.dcc`` and ``framework.contract_runner.federation``.
"""
